# Generated by Django 2.2 on 2019-10-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_model',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
