# Generated by Django 2.2 on 2019-10-07 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event_model_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_model',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_model',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
