# Generated by Django 2.2 on 2019-10-07 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191007_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_model',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='event_model',
            name='updated',
        ),
        migrations.AlterField(
            model_name='event_model',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
